repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/
      # Formatter
      - id: ruff-format
        files: ^backend/

  # Black - Python code formatter (fallback if ruff-format doesn't cover everything)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^backend/
        language_version: python3.11

  # detect-secrets - Prevent secrets from being committed
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            .*\.lock$|
            .*\.json$|
            .*/package-lock.json$|
            .*/yarn.lock$|
            .*/pnpm-lock.yaml$
          )$

  # nbstripout - Strip outputs from Jupyter notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: \.ipynb$

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements
        files: ^backend/

  # Frontend linting (if we add it later)
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       entry: npm run lint
  #       language: node
  #       files: ^frontend/.*\.(ts|tsx|js|jsx)$
  #       pass_filenames: false