services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - OFFLINE=0
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
      - SENTRY_ENVIRONMENT=development
      - RNG_SEED=42
    volumes:
      # Mount cache directories for development
      - ./features:/app/features
      - ./backend/logs:/app/logs
    networks:
      - f1-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_CLIENT_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ENABLE_SENTRY=false
      - NEXT_PUBLIC_SENTRY_ENVIRONMENT=development
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - f1-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  f1-network:
    driver: bridge
