# Railway deployment configuration
[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 60
  restartPolicyType = "ON_FAILURE"

[env]
  ENV = "production"
  CORS_ORIGINS = "${{RAILWAY_STATIC_URL}}"