services:
  - type: web
    name: f1-strategy-lab
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements-render.txt
    startCommand: cd backend && uvicorn app_minimal:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENF1_API_URL
        value: https://api.openf1.org/v1
      - key: ENV
        value: production
      - key: OFFLINE
        value: false
      - key: CORS_ORIGINS
        value: https://f1simulator-six.vercel.app,https://f1simulator-macqgkwov-favour01216s-projects.vercel.app
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: PIP_NO_CACHE_DIR
        value: "1"
    healthCheckPath: /health
