{
  "name": "f1-undercut-simulator",
  "services":
    [
      {
        "name": "backend",
        "source_dir": "backend",
        "dockerfile_path": "backend/Dockerfile",
        "http_port": 8000,
        "instance_count": 1,
        "instance_size_slug": "basic-xxs",
        "envs":
          [
            { "key": "ENV", "value": "production" },
            { "key": "CORS_ORIGINS", "value": "${_self.URL},${frontend.URL}" },
          ],
        "health_check": { "http_path": "/health" },
      },
      {
        "name": "frontend",
        "source_dir": "frontend",
        "dockerfile_path": "frontend/Dockerfile",
        "http_port": 3000,
        "instance_count": 1,
        "instance_size_slug": "basic-xxs",
        "envs": [{ "key": "NEXT_PUBLIC_API_URL", "value": "${backend.URL}" }],
      },
    ],
}
