name: ci-frontend

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm i --frozen-lockfile

      - name: Run linting
        working-directory: ./frontend
        run: pnpm run lint

      - name: Run type checking
        working-directory: ./frontend
        run: pnpm run typecheck

      - name: Build application
        working-directory: ./frontend
        run: pnpm run build

      - name: Check bundle size
        run: |
          # Add bundle analyzer if needed
          echo "Bundle size check would go here"

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run security audit
        run: npm audit --audit-level moderate
        working-directory: frontend
        continue-on-error: true
